apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ThiboSub/Nextcloud'
    targetRevision: HEAD
    path: .  # Chemin relatif à la racine du dépôt
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nextcloud  # Assurez-vous que ce namespace existe
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
