nextcloud:
  host: nextcloud.example.com
  username: admin
  password: SuperSecretPassword
  
mariadb:
  enabled: true
  auth:
    rootPassword: mariadb-root-password
    password: mariadb-password
    database: nextcloud
